### ISSUE TITLE
Virus Detected when downloading the zip file

### ISSUE THREAD

**Issue by gsaiganesh283** [poky1084/bot4stake#4]
![image](https://github.com/user-attachments/assets/5796ee7b-0d3e-426d-b72c-7a08600cdd41)

**Comment by poky1084** [comment]
False positive alert by microsoft defender. Can't do much about that.
https://www.virustotal.com/gui/file/9102a88c64e0862baa548fda64d54f21733ca28c82bbaefc439e94d4e4b91ba5?nocache=1

**Comment by poky1084** [comment]
False positive alert by microsoft defender. Can't do much about that.
https://www.virustotal.com/gui/file/f79dd05b0e92b60d5873fe6de7a3399988da5985bd7427524ea58513dc6beb53?nocache=1

**Comment by poky1084** [comment]
False positive alert by microsoft defender. Can't do much about that.
https://www.virustotal.com/gui/file/4e9498101457f87dd914b565b21b158c26cdf8dcbd9fe1d215f4adba93640877?nocache=1

**Comment by poky1084** [comment]
fixed it. it detects the file saver as a trojan, so i removed that code from index.js

**Comment by poky1084** [comment]
fixed it. it detects the file saver as a trojan, so i removed that code from index.js
